language: c
sudo: true
dist: xenial

os:
  - linux
  - osx
  - windows

before_install:
    - if [[ $TRAVIS_OS_NAME == linux ]]; then
        sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe";
        sudo apt-get update;
        sudo apt -q install fpc caskroom/cask/brew-cask;
        sudo apt -q install lazarus lcl-nogui;
      elif [[ $TRAVIS_OS_NAME == osx ]]; then
        brew update > /dev/null;
        brew install fpc > /dev/null;
        brew cask install fpcsrc lazarus > /dev/null;
      else
        wget -q ftp://ftp.freepascal.org/pub/fpc/snapshot/v33/i386-win32/fpc-3.3.1.i386-win32.zip;
        mkdir fpc;
        unzip -q -d fpc fpc-3.3.1.i386-win32.zip;
        export PATH="$PATH":"$PWD/fpc/bin/i386-win32/";
        wget -q ftp://ftp.freepascal.org/pub/fpc/source/lazarus.zip;
        mkdir lazarus
        unzip -q -d fpc lazarus.zip;
        export PATH="$PATH":"$PWD/lazarus";
        make;
      fi

install:
  - cd src/console
  - if [[ $TRAVIS_OS_NAME == linux ]]; then
      /usr/lib/lazarus/lazbuild SahysModConsole.lpr;
    elif [[ $TRAVIS_OS_NAME == osx ]]; then
      lazbuild SahysModConsole.lpr --widgetset=cocoa;
    else
      lazbuild;
    fi

script:
  - ./SahysModConsole "$PWD/test/example.inp" "$PWD/test/example.out"
