name: Compile SWAT+
on:
  push:
    branches:
      - githubActions
jobs:
  compile:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
      fail-fast: false

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Install Pascal
        uses: gcarreno/setup-lazarus@v3.2
        with:
          lazarus-version: "stable"
          include-packages: "Synapse 40.1"
          with-cache: true

      - name: Build
        run: lazbuild SahysModConsole.lpr
        if: runner.os != 'macOS'

      - name: Build macOS
        run: lazbuild SahysModConsole.lpr --widgetset=cocoa
        if: runner.os == 'macOS'

      - name: Test
        run: |
          ./SahysModConsole "test/example.inp" "test/example.out"
          if [[ -f "test/example.out" ]]; then
            echo "Output generated and all is well";
          else
            exit 1;
          fi
        shell: bash

      - name: Prepare release
        run: mkdir dist && mv ./SahysModConsole "./dist/SahysModConsole-$RUNNER_OS-$TRAVIS_TAG"

      - name: Release
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          artifacts: "dist/*"
