name: Compile Sahysmod
on:
  push:
    branches:
      - master
jobs:
  compile:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
      fail-fast: false

    steps:
      - name: Checkout project
        uses: actions/checkout@v6

      - name: MacOS env
        run: | 
          OPT="-XR/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/"
          echo "OPT=$OPT" >> $GITHUB_ENV 
        if: runner.os == 'macOS'

      - name: Install Pascal
        uses: gcarreno/setup-lazarus@v3
        with:
          lazarus-version: "stable"
          include-packages: "Synapse 40.1"
          with-cache: false

      - name: Build
        run: lazbuild src/console/SahysModConsole.lpr
        if: runner.os != 'macOS'

      - name: Build macOS
        run: lazbuild src/console/SahysModConsole.lpr --widgetset=cocoa
        if: runner.os == 'macOS'

      - name: Test
        run: |
          ./src/console/SahysModConsole "${GITHUB_WORKSPACE}/test/example.inp" "${GITHUB_WORKSPACE}/test/example.out"
          if [[ -f "test/example.out" ]]; then
            echo "Output generated and all is well";
          else
            exit 1;
          fi
        shell: bash

      - name: Test MacOS
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- ./src/console/SahysModConsole "${GITHUB_WORKSPACE}/test/example.inp" "${GITHUB_WORKSPACE}/test/example.out"
          if [[ -f "test/example.out" ]]; then
            echo "Output generated and all is well";
          else
            exit 1;
          fi
        shell: bash

      - name: Prepare release on Windows
        run: mkdir dist && mv ./src/console/SahysModConsole.exe "./dist/SahysModConsole.exe"
        if: runner.os == 'Windows'

      - name: Prepare release on all other platforms
        run: mkdir dist && mv ./src/console/SahysModConsole "./dist/SahysModConsole"
        if: runner.os != 'Windows'

      - name: Release
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          artifacts: "dist/*"
